TestOk/TestOk/Controllers/SharedController.cs
using BusinessLogic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace TestOk.Controllers
{
    public abstract class SharedController : Controller
    {
        private readonly ITestService _testService;

        protected SharedController(ITestService testService)
        {
            _testService = testService;
        }

        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            ViewBag.Subjects = _testService.GetCountedTestSubjects();
            base.OnActionExecuting(filterContext);
        }
    }
}

TestOk/TestOk/Controllers/StatisticsController.cs
using BusinessLogic;
using BusinessLogic.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using TestOk.Models;

namespace TestOk.Controllers
{
    public class StatisticsController : SharedController
    {
        private readonly ITestService _testService;
        private readonly IStatisticsService _statisticsService;

        public StatisticsController(ITestService testService, IStatisticsService statisticsService) : base(testService)
        {
            _statisticsService = statisticsService;
            _testService = testService;
        }

        public IActionResult GetCurrent(int surveyID = 1)
        {
            var userId = User.Identity.GetUserId();

            var average = _statisticsService.GetAverageMark(userId);
            int toPass = 0;
            int forCertain = 0;
            try
            {
                forCertain = _statisticsService.GetMarkForTest(surveyID, userId);
                toPass = _statisticsService.GetMarkToPass(surveyID, userId); 
            }
            catch
            {
                return View(new StatisticsModel
                {
                    AverageMark = average,
                    ForCertain = 0,
                    CurrentSurveyID = surveyID,
                    ToPass = toPass
                });
            }
            return View(new StatisticsModel
            {
                AverageMark = average,
                ForCertain = forCertain,
                CurrentSurveyID = surveyID,
                ToPass = toPass
            });
        }
    }
}

TestOk/TestOk/Controllers/TestController.cs
using BusinessLogic;
using DataAccess.DTO;
using Microsoft.AspNetCore.Mvc;

namespace TestOk.Controllers
{
    public class TestController : SharedController
    {
        private readonly ITestService _testService;
        public TestController(ITestService testService) : base(testService)
        {
            _testService = testService;
        }
        public ActionResult Create()
        {
            return View(new TestDto());
        }

        [HttpPost]
        public IActionResult Create(TestDto testDto)
        {
            if (ModelState.IsValid && TryValidateModel(testDto.Quizes))
            {
                _testService.SaveTest(testDto);

                return RedirectToAction("Create");
            }

            return View(testDto);
        }
    }
}

TestOk/TestOk/Views/Shared/CreateQuiz.cshtml
@model DataAccess.DTO.QuizDto

@{
    ViewData["Title"] = "AddQuiz";
}

@using (Html.BeginCollectionItem("quizes"))
{
	<li class="list-group-item quizRow">
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
			<label asp-for="Question" class="control-label"></label>
            <input asp-for="Question" class="form-control" />
			<span asp-validation-for="Question" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="PointsPerCorrectAnswer" class="control-label"></label>
			<input asp-for="PointsPerCorrectAnswer" type="number" class="form-control" />
			<span asp-validation-for="PointsPerCorrectAnswer" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Complexity" class="control-label"></label>
			<input asp-for="Complexity" type="number" class="form-control" />
			<span asp-validation-for="Complexity" class="text-danger"></span>
		</div>
		<button class="btn btn-warning deleteQuiz">Remove</button>
	</li>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestOk/TestOk/Views/Shared/CreateTest.cshtml
@model DataAccess.DTO.TestDto

@{
    ViewData["Title"] = "AddTest";
}

@using (@Html.BeginForm("", "SaveTest", FormMethod.Post))
    {
	<div class="row">
		<div class="col-md-4">
			<h2>New Test</h2>
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="MaxGrade" class="control-label"></label>
				<input asp-for="MaxGrade" type="number" class="form-control" />
				<span asp-validation-for="MaxGrade" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Subject" class="control-label"></label>
				<input asp-for="Subject" class="form-control" />
				<span asp-validation-for="Subject" class="text-danger"></span>
			</div>
	        <div class="form-group">
		        <label asp-for="MinimumSuccessPercentage" class="control-label"></label>
			    <input asp-for="MinimumSuccessPercentage" type="number"  class="form-control" />
				<span asp-validation-for="MinimumSuccessPercentage" class="text-danger"></span>
			</div>
			<div>
				<button type="submit" class="btn btn-primary">Save</button>
				<button type="reset" class="btn btn-danger">Clear</button>
			</div>
		</div>

		<div class="col-md-8">
			<div id="quizes" class="text-center">
				<h2>Quizes</h2>
				<ul class="list-group mt-5">
					@foreach (var quiz in Model.Quizes) { Html.RenderPartial("AddQuiz", quiz); }
				</ul>
			</div>
			<div class="text-center">
				<button id="addQuiz" class="btn btn-secondary">Add Quiz</button>
			</div>
		</div>

	</div>
}

@section Scripts
{
	<script>
		$("#addQuiz").on("click", function (event) {
			event.preventDefault();

			$.ajax({
                async: false,
                url: '/CreateQuiz',
				success: function (partialView) {
					$('#quizes').append(partialView);
				}
			})			
		});
	</script>

	<script>
		$(document).on("click", "button.deleteQuiz", function(){
			$(this).parents("li.quizRow:first").remove();
			return false;
		});
	</script>

	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestOk/TestOk/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestOk</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/home.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/mega-menu.css" />
    <link rel="stylesheet" type="text/css" href="~/css/survey.css" />

    <script src="~/js/mega_menu.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestOk</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Create">Create Test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="GetCurrent">Statistics</a>
                        </li>
                        <li class="nav-item">
                            <div class="col-10" id="testsButton">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Tests" asp-route-subject="">Tests</a>
                                <div class="tests-container">
                                    @foreach (var el in @ViewBag.Subjects ?? new List<DataAccess.Data.DTO.CountedSubjectDto>())
                                    {
                                        <div class="test-item">
                                            <a id="item-text" asp-controller="Home" asp-action="Tests" asp-route-subject="@el.Subject">@el.Subject (@el.Count)</a>
                                        </div>
                                    }
                                </div>
                            </div>
                        </li>

                        @if (User.IsInRole("teacher"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Create">Create Test</a>
                            </li>
                        }
                        @if (User.IsInRole("teacher") || User.IsInRole("student"))
                        {
                            <li class="nav-item">
                                <div class="col-10" id="testsButton">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Tests" asp-route-subject="">Tests</a>
                                    <div class="tests-container">
                                        @foreach (var el in @ViewBag.Subjects ?? new List<DataAccess.Data.DTO.CountedSubjectDto>())
                                        {
                                            <div class="test-item">
                                                <a id="item-text" asp-controller="Home" asp-action="Tests" asp-route-subject="@el.Subject">@el.Subject (@el.Count)</a>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @{
        bool isHomePage = @Html.ViewContext.HttpContext.Request.Path.Equals("/");

        <div class="@(isHomePage ? "": "container mt-3")">
            <main role="main" class="@(isHomePage ? "": "pb-3")">
                @RenderBody()
            </main>
        </div>
    }

<footer class="border-top footer text-muted row pt-3">
    <div class="col-12 col-md-6 text-center">
        &copy; 2020 - TestOk - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    <div class="col-12 col-md-6 text-center d-flex flex-column">
        <h6>Created By</h6>
        <p>
            Andriy Pasternak
        </p>
        <p>
            Nazar Vivchar
        </p>
        <p>
            Taras Bat
        </p>
        <p>
            Yuriy Horoshko
        </p>
    </div>
</footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TestOk/TestOk/Views/Shared/Tests.cshtml
@model TestsModel
@{
    ViewData["Title"] = "Available tests";
}
<h1>@ViewData["Title"]</h1>
<p>@Model.Title</p>
<div class="container mt-3 tests-page-container">
    @foreach (var test in Model.Tests)
    {
        <div class="test-item-body">
            <div class="flex-lg-row">
                <strong class="flex-lg-row">@test.Subject.ToUpper()</strong>
            </div>
            <div class="row" style="height: 75%;">
                <div class="col-8" style="height: 100%">
                    <div class="flex-md-row min-text-size" >
                        <span class="test-body-text text-justify" style="margin-bottom: 15px">
                            In order to successfully pass this test
                            You need to score at least
                            <strong>
                                @Model.GetMinPoints(test) of
                            @test.MaxGrade points
                        </strong>.
                        Please, don`t use any forbidden things
                        and don`t switch tabs in browser (you can actually,
                        but in future we will BAN you for this :) )
                        </span>
                    </div>
                    <div class="flex-md-row min-text-size">
                        <strong>Minimum percentage to pass this test: @test.MinimumSuccessPercentage%</strong>
                    </div>
                </div>
                <div class="col-4" style="height: 100%">
                    <div class="row" style="height: 50%; align-content: flex-end">
                        <strong class="text-justify test-btn-proceed">
                            Maximum grade: @test.MaxGrade
                        </strong>
                    </div>
                    <div class="row" style="height: 50%; align-content: center">
                        <button type="button" class="btn btn-dark test-btn-proceed" onclick="location.href = '@Url.Action("GetSurvey", "Survey", new { testId = test.Id })'">Proceed</button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

TestOk/TestOk/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestOk</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestOk</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TestOk - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>